### PR TITLE
Make missing pointerlock a noop.

### PR DESCRIPTION
**Pull request by jdalton**
Since the benchmark doesn't use pointerlock I went ahead and made it work without it.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

Btw, this demo is a little out of date by now. We should update it with a new build, if people are using it to benchmark? (until your pull request I wasn't sure if people were)

**Comment by jdalton** [comment]
> Btw, this demo is a little out of date by now. We should update it with a new build

I noticed there were some textures missing. Btw if you're updating would it be possible to convert the audio to -all- mp3/wav. Currently there's a mix of formats and in IE at least it sounds like just a bunch of grunting.

Should I create a PR for gh-pages or is it easier for you to git-fu it?

**Comment by jdalton** [comment]
> Btw, this demo is a little out of date by now. We should update it with a new build

I noticed there were some textures missing. Btw if you're updating can you convert the audio to -all- mp3. Right now there is a mix of formats and in IE it sounds like just a bunch of grunting.

**Comment by jdalton** [comment]
Should I create a PR for gh-pages or is it easier for you to git-fu it?

**Comment by jdalton** [comment]
Ping?

**Comment by kripken** [comment]
(Sorry for the delay, busy few days over here.)

Hmm, converting the audio to mp3 might make it stop working in some browsers, though? I don't think they all support mp3 today?

**Comment by jdalton** [comment]
Looks like [they do](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP3) (IE, Firefox, Safari, Chrome). Though there is an \* next to FF with a note about the OS needing to support MP3 playback. If not maybe a fallback but that get's more complicated.

**Comment by kripken** [comment]
The OS support worries me. I guess the best thing would be to ship one format + a polyfill for the other? Not sure what games generally do about this. Any chance IE will support ogg?

Meanwhile I pushed a new build, which also fixes the broken textures.

**Comment by jdalton** [comment]
> Any chance IE will support ogg?

Probably slim. Though https://status.modern.ie/wavaudiosupport?term=wav looks to be available in preview releases so could be an option.

> Meanwhile I pushed a new build, which also fixes the broken textures.

Nice!

**Comment by kripken** [comment]
Ok. I'm actually not sure offhand if cube2 supports wav or mp3, we would need to check. Although, another option is to just disable sound in this benchmark I guess, but benchmarking audio is valuable as well (there are some current Web Audio slowness issues in firefox for example).

**Pull request merged**
